development:
  adapter: mysql2
  encoding: utf8
  database: wedding_agency
  pool: 5
  username: root
  password:
  host: 127.0.0.1
production:
  adapter: mysql2
  encoding: utf8
  database: wedding_agency
  pool: 5
  username: root
  password:
  host: 127.0.0.1
